# Generated by Django 2.0.7 on 2018-07-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='words',
            field=models.TextField(default='[{}]'),
        ),
    ]
