# Generated by Django 2.0.7 on 2018-07-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='player',
        ),
        migrations.AlterField(
            model_name='mission',
            name='count_of_words',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='lang',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mode',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='result',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='step',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='words',
            field=models.TextField(),
        ),
    ]
