# Generated by Django 2.0.7 on 2018-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_auto_20180710_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='dictionary',
            field=models.TextField(default='workbook'),
        ),
    ]
