# Generated by Django 2.2.7 on 2019-11-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_mission_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='start_time'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='dictionary',
            field=models.TextField(default='university'),
        ),
    ]
