# Generated by Django 2.0.7 on 2018-08-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_mission_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='dictionary',
            field=models.TextField(default='IT'),
        ),
    ]
