# Generated by Django 2.2.7 on 2019-11-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_auto_20180831_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='dictionary',
            field=models.TextField(default='university'),
        ),
    ]
