# Generated by Django 2.2.7 on 2019-11-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_auto_20191114_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='finish_time',
            field=models.DateTimeField(default=None, verbose_name='finish_time'),
        ),
        migrations.AddField(
            model_name='mission',
            name='start_time',
            field=models.DateTimeField(default=None, verbose_name='start_time'),
        ),
    ]
