# Generated by Django 2.2.7 on 2019-11-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_auto_20191114_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='finish_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='finish_time'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='start_time'),
        ),
    ]
