# Generated by Django 2.2.7 on 2019-11-14 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_auto_20191114_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 19, 49, 32, 727758, tzinfo=utc), null=True, verbose_name='finish_time'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 19, 49, 32, 727583, tzinfo=utc), null=True, verbose_name='start_time'),
        ),
    ]
