# Generated by Django 2.2.7 on 2019-11-14 20:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0014_auto_20191114_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='finish_time',
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 20, 17, 45, 187066, tzinfo=utc), null=True, verbose_name='start_time'),
        ),
    ]
