# Generated by Django 2.2.7 on 2019-11-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0015_auto_20191114_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='start_time'),
        ),
    ]
